services:
  server:
    image: alpine:latest
    container_name: server
    command: sh /app/server.sh
    volumes:
      - ./server:/app
      - ./shared_keys:/shared_keys
    networks:
      server_net:
        ipv4_address: 172.20.0.2

  client:
    image: alpine:latest
    container_name: client
    command: sh /app/client.sh
    volumes:
      - ./client:/app
      - ./shared_keys:/shared_keys
    networks:
      client_net:
        ipv4_address: 172.22.0.2

  attacker:
    image: alpine:latest
    container_name: attacker
    command: sh /app/attacker.sh
    volumes:
      - ./attacker:/app
    networks:
      server_net:
        ipv4_address: 172.20.0.3
      client_net:
        ipv4_address: 172.22.0.3
    cap_add:             # Required for packet capture
      - NET_ADMIN
    stdin_open: true
    tty: true

networks:
  server_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  client_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16